/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'condition' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'filterListingsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'filterListingsByCategoryAndPriceRange' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'filterListingsByCondition' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'filterListingsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'filterListingsByLocationAndCondition' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'filterListingsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllConditions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getListingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getListingsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getListingsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getNewestListings' : IDL.Func([IDL.Nat], [IDL.Vec(Listing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFilterListings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'searchListingsByText' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'updateListing' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'condition' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'filterListingsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'filterListingsByCategoryAndPriceRange' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'filterListingsByCondition' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'filterListingsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'filterListingsByLocationAndCondition' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'filterListingsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllConditions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getListingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getListingsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getListingsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getNewestListings' : IDL.Func([IDL.Nat], [IDL.Vec(Listing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFilterListings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'searchListingsByText' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'updateListing' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };