/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Listing {
  'id' : bigint,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'price' : bigint,
  'location' : string,
  'condition' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, string, bigint, string, string, string],
    bigint
  >,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'filterListingsByCategory' : ActorMethod<[string], Array<Listing>>,
  'filterListingsByCategoryAndPriceRange' : ActorMethod<
    [string, bigint, bigint],
    Array<Listing>
  >,
  'filterListingsByCondition' : ActorMethod<[string], Array<Listing>>,
  'filterListingsByLocation' : ActorMethod<[string], Array<Listing>>,
  'filterListingsByLocationAndCondition' : ActorMethod<
    [string, string],
    Array<Listing>
  >,
  'filterListingsByPriceRange' : ActorMethod<[bigint, bigint], Array<Listing>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllConditions' : ActorMethod<[], Array<string>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllLocations' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[bigint], [] | [Listing]>,
  'getListingCount' : ActorMethod<[], bigint>,
  'getListingsByOwner' : ActorMethod<[Principal], Array<Listing>>,
  'getListingsPaginated' : ActorMethod<[bigint, bigint], Array<Listing>>,
  'getNewestListings' : ActorMethod<[bigint], Array<Listing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFilterListings' : ActorMethod<
    [string, string, string, string, bigint, bigint],
    Array<Listing>
  >,
  'searchListingsByText' : ActorMethod<[string], Array<Listing>>,
  'updateListing' : ActorMethod<
    [bigint, string, string, bigint, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];